#################### @BEGIN GEN PINS@ ####################
set_property PACKAGE_PIN H1        [ get_ports         "brd_rev[0]" ] ;
set_property PULLUP      "TRUE"   [ get_ports         "brd_rev[0]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports         "brd_rev[0]" ] ;
set_property PACKAGE_PIN P7        [ get_ports         "brd_rev[1]" ] ;
set_property PULLUP      "TRUE"   [ get_ports         "brd_rev[1]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports         "brd_rev[1]" ] ;
set_property PACKAGE_PIN R7        [ get_ports         "brd_rev[2]" ] ;
set_property PULLUP      "TRUE"   [ get_ports         "brd_rev[2]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports         "brd_rev[2]" ] ;
set_property PACKAGE_PIN R8        [ get_ports         "brd_rev[3]" ] ;
set_property PULLUP      "TRUE"   [ get_ports         "brd_rev[3]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports         "brd_rev[3]" ] ;
set_property PACKAGE_PIN C3        [ get_ports             "pmod_1" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports             "pmod_1" ] ;
set_property PACKAGE_PIN R4        [ get_ports             "pmod_2" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports             "pmod_2" ] ;
set_property PACKAGE_PIN P8        [ get_ports             "pmod_3" ] ;
set_property PULLUP      "TRUE"   [ get_ports             "pmod_3" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports             "pmod_3" ] ;
set_property PACKAGE_PIN M7        [ get_ports             "pmod_4" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports             "pmod_4" ] ;
set_property PACKAGE_PIN B4        [ get_ports             "pmod_7" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports             "pmod_7" ] ;

#LMS connections
set_property PACKAGE_PIN L2        [ get_ports        "lms_dig_rst" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "lms_dig_rst" ] ;
set_property PACKAGE_PIN K8        [ get_ports        "lms_hw_rxen" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "lms_hw_rxen" ] ;
set_property PACKAGE_PIN N8        [ get_ports        "lms_hw_txen" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "lms_hw_txen" ] ;
set_property PACKAGE_PIN E2        [ get_ports      "clkbuff_rst_n" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "clkbuff_rst_n" ] ;
set_property PACKAGE_PIN D2        [ get_ports       "clkbuff_lock" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "clkbuff_lock" ] ;
set_property PACKAGE_PIN B2        [ get_ports        "clkbuff_irq" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "clkbuff_irq" ] ;
set_property PACKAGE_PIN A1        [ get_ports       "fpga_red_led" ] ;
set_property PULLUP      "TRUE"   [ get_ports       "fpga_red_led" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "fpga_red_led" ] ;
set_property PACKAGE_PIN D1        [ get_ports     "fpga_grn_led_n" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "fpga_grn_led_n" ] ;
set_property PACKAGE_PIN A4        [ get_ports     "rfmod_gpio[10]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[10]" ] ;
set_property PACKAGE_PIN A5        [ get_ports      "rfmod_gpio[4]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[4]" ] ;
set_property PACKAGE_PIN A6        [ get_ports      "rfmod_gpio[3]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[3]" ] ;
set_property PACKAGE_PIN A7        [ get_ports      "rfmod_gpio[1]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[1]" ] ;
set_property PACKAGE_PIN B6        [ get_ports      "rfmod_gpio[2]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[2]" ] ;
set_property PACKAGE_PIN B7        [ get_ports      "rfmod_gpio[6]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[6]" ] ;
set_property PACKAGE_PIN B8        [ get_ports     "rfmod_gpio[16]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[16]" ] ;
set_property PACKAGE_PIN C4        [ get_ports      "rfmod_gpio[9]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[9]" ] ;
set_property PACKAGE_PIN C5        [ get_ports     "rfmod_gpio[11]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[11]" ] ;
set_property PACKAGE_PIN C6        [ get_ports     "rfmod_gpio[13]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[13]" ] ;
set_property PACKAGE_PIN C8        [ get_ports      "rfmod_gpio[5]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[5]" ] ;
set_property PACKAGE_PIN D5        [ get_ports     "rfmod_gpio[12]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[12]" ] ;
set_property PACKAGE_PIN E5        [ get_ports      "rfmod_gpio[8]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[8]" ] ;
set_property PACKAGE_PIN F5        [ get_ports     "rfmod_gpio[15]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[15]" ] ;
set_property PACKAGE_PIN F6        [ get_ports     "rfmod_gpio[14]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "rfmod_gpio[14]" ] ;
set_property PACKAGE_PIN G6        [ get_ports      "rfmod_gpio[7]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "rfmod_gpio[7]" ] ;
set_property PACKAGE_PIN L6        [ get_ports       "lms_spi_sclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "lms_spi_sclk" ] ;
set_property PACKAGE_PIN L7        [ get_ports       "lms_spi_sdio" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "lms_spi_sdio" ] ;
set_property PACKAGE_PIN R5        [ get_ports        "lms_spi_sdo" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "lms_spi_sdo" ] ;
set_property PACKAGE_PIN M8        [ get_ports        "lms_spi_sen" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "lms_spi_sen" ] ;
set_property PACKAGE_PIN K5        [ get_ports  "lms_diq1_iqseldir" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "lms_diq1_iqseldir" ] ;
set_property PACKAGE_PIN L5        [ get_ports      "lms_diq1_mclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_mclk" ] ;
set_property PACKAGE_PIN K4        [ get_ports      "lms_diq1_fclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_fclk" ] ;
set_property PACKAGE_PIN P2        [ get_ports     "lms_diq1_txnrx" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq1_txnrx" ] ;
set_property PACKAGE_PIN J5        [ get_ports      "lms_diq1_d[9]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[9]" ] ;
set_property PACKAGE_PIN K2        [ get_ports      "lms_diq1_d[7]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[7]" ] ;
set_property PACKAGE_PIN M1        [ get_ports      "lms_diq1_d[6]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[6]" ] ;
set_property PACKAGE_PIN M2        [ get_ports      "lms_diq1_d[2]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[2]" ] ;
set_property PACKAGE_PIN N1        [ get_ports      "lms_diq1_d[3]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[3]" ] ;
set_property PACKAGE_PIN N5        [ get_ports      "lms_diq1_d[8]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[8]" ] ;
set_property PACKAGE_PIN N6        [ get_ports     "lms_diq1_d[11]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq1_d[11]" ] ;
set_property PACKAGE_PIN P1        [ get_ports      "lms_diq1_d[1]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[1]" ] ;
set_property PACKAGE_PIN P3        [ get_ports      "lms_diq1_d[0]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[0]" ] ;
set_property PACKAGE_PIN P6        [ get_ports      "lms_diq1_d[4]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[4]" ] ;
set_property PACKAGE_PIN R2        [ get_ports      "lms_diq1_d[5]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq1_d[5]" ] ;
set_property PACKAGE_PIN R3        [ get_ports     "lms_diq1_d[10]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq1_d[10]" ] ;
set_property PACKAGE_PIN J6        [ get_ports  "lms_diq2_iqseldir" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "lms_diq2_iqseldir" ] ;
set_property PACKAGE_PIN T2        [ get_ports      "lms_diq2_mclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_mclk" ] ;
set_property PACKAGE_PIN U2        [ get_ports      "lms_diq2_fclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_fclk" ] ;
set_property PACKAGE_PIN J1        [ get_ports     "lms_diq2_txnrx" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq2_txnrx" ] ;
set_property PACKAGE_PIN J2        [ get_ports     "lms_diq2_d[11]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq2_d[11]" ] ;
set_property PACKAGE_PIN J3        [ get_ports      "lms_diq2_d[8]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[8]" ] ;
set_property PACKAGE_PIN J7        [ get_ports      "lms_diq2_d[0]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[0]" ] ;
set_property PACKAGE_PIN J8        [ get_ports      "lms_diq2_d[9]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[9]" ] ;
set_property PACKAGE_PIN K7        [ get_ports      "lms_diq2_d[5]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[5]" ] ;
set_property PACKAGE_PIN L1        [ get_ports     "lms_diq2_d[10]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports     "lms_diq2_d[10]" ] ;
set_property PACKAGE_PIN M3        [ get_ports      "lms_diq2_d[6]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[6]" ] ;
set_property PACKAGE_PIN M4        [ get_ports      "lms_diq2_d[7]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[7]" ] ;
set_property PACKAGE_PIN M6        [ get_ports      "lms_diq2_d[3]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[3]" ] ;
set_property PACKAGE_PIN N3        [ get_ports      "lms_diq2_d[4]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[4]" ] ;
set_property PACKAGE_PIN N4        [ get_ports      "lms_diq2_d[2]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[2]" ] ;
set_property PACKAGE_PIN P5        [ get_ports      "lms_diq2_d[1]" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports      "lms_diq2_d[1]" ] ;

#silabs gt reference
set_property PACKAGE_PIN U9        [ get_ports       "mgtrefclk0_p" ] ;
set_property PACKAGE_PIN V9        [ get_ports       "mgtrefclk0_n" ] ;

#backplane connections
set_property PACKAGE_PIN AA3       [ get_ports         "mgttx_p[0]" ] ;
set_property PACKAGE_PIN AA5       [ get_ports         "mgttx_p[2]" ] ;
set_property PACKAGE_PIN W2        [ get_ports         "mgttx_p[3]" ] ;
set_property PACKAGE_PIN W4        [ get_ports         "mgttx_p[1]" ] ;
set_property PACKAGE_PIN AB3       [ get_ports         "mgttx_n[0]" ] ;
set_property PACKAGE_PIN AB5       [ get_ports         "mgttx_n[2]" ] ;
set_property PACKAGE_PIN Y2        [ get_ports         "mgttx_n[3]" ] ;
set_property PACKAGE_PIN Y4        [ get_ports         "mgttx_n[1]" ] ;
set_property PACKAGE_PIN AA7       [ get_ports         "mgtrx_p[0]" ] ;
set_property PACKAGE_PIN AA9       [ get_ports         "mgtrx_p[2]" ] ;
set_property PACKAGE_PIN W6        [ get_ports         "mgtrx_p[3]" ] ;
set_property PACKAGE_PIN W8        [ get_ports         "mgtrx_p[1]" ] ;
set_property PACKAGE_PIN AB7       [ get_ports         "mgtrx_n[0]" ] ;
set_property PACKAGE_PIN AB9       [ get_ports         "mgtrx_n[2]" ] ;
set_property PACKAGE_PIN Y6        [ get_ports         "mgtrx_n[3]" ] ;
set_property PACKAGE_PIN Y8        [ get_ports         "mgtrx_n[1]" ] ;

#uplink feedback clock
set_property PACKAGE_PIN E7        [ get_ports  "icnt_up_aux_clk_n" ] ;
set_property IOSTANDARD  LVDS     [ get_ports  "icnt_up_aux_clk_n" ] ;
set_property PACKAGE_PIN F7        [ get_ports  "icnt_up_aux_clk_p" ] ;
set_property IOSTANDARD  LVDS     [ get_ports  "icnt_up_aux_clk_p" ] ;

#uplink IO
set_property PACKAGE_PIN B3        [ get_ports  "icnt_up_psnt_n_in" ] ;
set_property PULLUP      "TRUE"   [ get_ports  "icnt_up_psnt_n_in" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "icnt_up_psnt_n_in" ] ;
set_property PACKAGE_PIN G8        [ get_ports       "icnt_up_sclk" ] ;
set_property PULLUP      "TRUE"   [ get_ports       "icnt_up_sclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "icnt_up_sclk" ] ;
set_property PACKAGE_PIN D8        [ get_ports  "icnt_up_is_head_n" ] ;
set_property PULLUP      "TRUE"   [ get_ports  "icnt_up_is_head_n" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "icnt_up_is_head_n" ] ;
set_property PACKAGE_PIN D7        [ get_ports "icnt_up_psnt_n_out" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports "icnt_up_psnt_n_out" ] ;
set_property PACKAGE_PIN E8        [ get_ports        "icnt_up_sda" ] ;
set_property PULLUP      "TRUE"   [ get_ports        "icnt_up_sda" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "icnt_up_sda" ] ;

#dnlink IOs
set_property PACKAGE_PIN F4        [ get_ports  "icnt_dn_psnt_n_in" ] ;
set_property PULLUP      "TRUE"   [ get_ports  "icnt_dn_psnt_n_in" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "icnt_dn_psnt_n_in" ] ;
set_property PACKAGE_PIN H3        [ get_ports        "icnt_dn_sda" ] ;
set_property PULLUP      "TRUE"   [ get_ports        "icnt_dn_sda" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "icnt_dn_sda" ] ;
set_property PACKAGE_PIN D3        [ get_ports "icnt_dn_psnt_n_out" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports "icnt_dn_psnt_n_out" ] ;
set_property PACKAGE_PIN E3        [ get_ports       "icnt_dn_sclk" ] ;
set_property PULLUP      "TRUE"   [ get_ports       "icnt_dn_sclk" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports       "icnt_dn_sclk" ] ;
set_property PACKAGE_PIN G3        [ get_ports    "icnt_dn_trigger" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports    "icnt_dn_trigger" ] ;
set_property PACKAGE_PIN G4        [ get_ports        "icnt_dn_aux" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports        "icnt_dn_aux" ] ;
set_property PACKAGE_PIN G2        [ get_ports  "icnt_dn_is_tail_n" ] ;
set_property PULLUP      "TRUE"   [ get_ports  "icnt_dn_is_tail_n" ] ;
set_property IOSTANDARD  LVCMOS18 [ get_ports  "icnt_dn_is_tail_n" ] ;

#################### @END GEN PINS@   ####################

## rfmod ID -- pulldown so that pins read 0x00 when nothing is attached
set_property PULLDOWN TRUE [get_ports {rfmod_gpio[1]}]
set_property PULLDOWN TRUE [get_ports {rfmod_gpio[2]}]
set_property PULLDOWN TRUE [get_ports {rfmod_gpio[3]}]
set_property PULLDOWN TRUE [get_ports {rfmod_gpio[4]}]
