% TRIAL1_SINEWAAVESRC Trial 1 - Read in the .out file generated by
% Trial1_SinewaveSrc.grc and plot the data.
%
% Yaguang Zhang, Purdue, 06/07/2017

% Load data and set the current Matlab directory.
cd(fileparts(mfilename('fullpath')));
addpath(fullfile(pwd));
addpath(fullfile(pwd, '..', '..', 'gnuradio-tools', 'matlab'));

filePath = fullfile(pwd, 'Test2_baseband_rx_file_sink_Mod_1497299569.out');

v = read_complex_binary(filePath);

vToPlot = v(1:100000);
figure;
hold on;
plot(real(vToPlot), 'b-');
plot(imag(vToPlot), 'r-.');
legend('Real','Image');
% EOF