#!/usr/bin/env bash

[ $# -ge 2 ] || { echo "usage: $(basename $0) start-node-# stop-node-#" 1>&2; exit 1; }

START=$1
STOP=$2

for ((i=$START;i<=$STOP;i++)); do
  echo "Stopping on radio$i"
  ssh radio$i "sudo pkill -TERM bamradio; sudo pkill ping; sudo pkill random_udp.sh ; sudo pkill iperf3; sudo pkill tcpdump; sudo pkill nc"
done

sleep 10

for ((i=$START;i<=$STOP;i++)); do
  echo "Stopping on radio$i"
  ssh radio$i sudo pkill -TERM bamradio
done
