#!/usr/bin/env bash

[ $# -ge 5 ] || { exit 1; }

SGLPREF=$1
ID=$2
SRNID=$((100+ID))
DSTID=$3
DSTID2=$4
SRNTUNADDR=192.168.$((100+ID)).32
DSTADDR=192.168.$((100+DSTID)).32
DSTADDR2=192.168.$((100+DSTID2)).32
USRPADDR=172.23.$((201+ID)).2
BUILD=$5

mkdir -p ${SGLPREF}bam-radio/sgl.test/radio$ID
cd ${SGLPREF}bam-radio/sgl.test/radio$ID

exec > out 
exec 2>&1

. /bamw/env.rel

echo "Starting radio$ID on $(date)"

#ethtool -g ens5

echo "$(hostname): Trying $USRPADDR"
sleep 1
uhd_find_devices --args=addr=$USRPADDR || { echo "******* $ID no USRP? *********************"; exit 1; }

sleep 5

ulimit -c unlimited

[ -f core ] && sudo rm core
sudo rm *.log *.out

bash -c "sleep 10 && sudo tcpdump -i tun0 -w tun0.out" &

#bash -c "sleep 5 && ${SGLPREF}bam-radio/sgl.test/random_udp.sh $DSTADDR 80" &
#bash -c "sleep 5 && sudo ping -s 1472 -M do -f -I tun0 -r $DSTADDR > /dev/null" &
#bash -c "sleep 5 && sudo ping -s 16000 -M dont -f -I tun0 -r $DSTADDR > /dev/null" &
#bash -c "sleep 5 && sudo ping -s 1000 -M do -f -I tun0 -r -i 0.001 $DSTADDR > /dev/null" &
#bash -c "sleep 5 && sudo ping -s 1472 -M do -i 0.005 -I tun0 -r $DSTADDR > /dev/null" &

#bash -c "sleep 20 && sudo iperf3 -s > iperftcpserv.out" &
#bash -c "sleep 60; sudo iperf3 -c $DSTADDR -t 120 --tos 0x33 > iperftcpclient.out" &

#bash -c "sleep 20 && sudo iperf3 -s -p 5202 > iperfudpserv.out" &
#bash -c "sleep 60; sudo iperf3 -c $DSTADDR -t 90 --tos 0x41 -u -b 3M -p 5202 > iperfudpclient.out" &

bash -c "sleep 30;  cat /dev/urandom | sudo nc -l -T 0x33 $SRNTUNADDR 5201 > /dev/null" &
bash -c "sleep 35;  cat /dev/urandom | sudo nc    -T 0x33 -P 5202 $DSTADDR 5201 > /dev/null" &
bash -c "sleep 105; cat /dev/urandom | sudo nc -l -T 0x33 $SRNTUNADDR 5203 > /dev/null" &
bash -c "sleep 110; cat /dev/urandom | sudo nc    -T 0x93 -P 5204 $DSTADDR 5203 > /dev/null" &
bash -c "sleep 145; cat /dev/urandom | sudo nc -l -T 0x33 $SRNTUNADDR 5205 > /dev/null" &
bash -c "sleep 150; cat /dev/urandom | sudo nc    -T 0x13 -P 5206 $DSTADDR2 5205 > /dev/null" &

sudo ${SGLPREF}build$BUILD/src/bamradio --config ../radio.conf --phy.args=addr=$USRPADDR --phy_control.id=$ID --net.tun-ip4=$SRNTUNADDR
